name: amap_search_fluttify_example
description: Demonstrates how to use the amap_search_fluttify plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^6.1.3
  decorated_flutter: ^0.28.0-pre.1
  amap_search_fluttify:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
