name: amap_search_fluttify
description: An `Amap` Search Component, Powered By `Fluttify` Engine, A Dart Bindings Generator for Native SDK.
version: 0.18.0-dev.0
authors:
  - yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_search_fluttify

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"

dependencies:
  flutter:
    sdk: flutter
  
  
  foundation_fluttify: ^0.13.0-dev.6
  core_location_fluttify: ^0.7.0-dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_search_fluttify
        pluginClass: AmapSearchFluttifyPlugin
      ios:
        pluginClass: AmapSearchFluttifyPlugin